In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)


['bat', 'bot']


In [7]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result
    

In [15]:
from numpy import random
import numpy as np

a = random.randint(100, size = (20, 20))
b = random.randint(300, size = (20, 20))
print(a)
print(b)

[[ 2 27 74 30 85 69 70 86 71  5 18 46 29 99 94 17 86 24 54 81]
 [ 8 86 52 76 11 84 26 84 98 77 76 10 80 42 51 29 48 94 26 17]
 [ 7 30 44  8 85 28 63 67 51 41 26 35 13 85  1 83 88 73 77 35]
 [64  5  6 48 39 39 62  5 57 38 82 30 84 91 99  1 22  0 26 58]
 [92 90 77 58  9 69  3 42 37 33 48 88 81 85 14  0 66 13 23 48]
 [97 32 83 68 13 19 57 20 94 49  1 85 44 86 41 70 68 20 75 84]
 [40 84 61 47 72 25 72 76 82 53 58  5 47 75 81 22  1 79 22 49]
 [95 48 79 57 18 23  7 47 19 33 54 12 98 56 47 38  7 29 76 88]
 [95 86 31 95  5 15 28  9 81 77 56 54 77  5 31 27 27 76 87 39]
 [89  3 88 91 34 93 17 23 23 22 95 16 85 40 71 43 30 25 89  2]
 [26 89  2  8 63 88 40 23 97 53 80 70 72 68 41  8 85 42  4 61]
 [18 81 75 94 59 18 43  2 60 63 32 69 29 87 90 52 42 97 61 29]
 [33  4 29 37 14 97 88  0  8 65 64 80 66  1  5 11 14 73  1 12]
 [85 19 96 45 41 73 41 17 37  6 10 34 78 79 89 25 72 48 42 48]
 [77 43 81  7 42 54 14 39 30 85 65 75 79 95 17 98 38 26 35 29]
 [31 23 67  7 91 52 34 57 76 72 58 37 18 14 28 56 70 36

In [29]:
np.random.seed(5652341)
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)
# print(a1)
# print(a2)
# print(a3)
# print(a4)
# print(a5)

[1 2 3]


In [25]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)

(4, 1)
(4, 1)
(1, 4)
(3,)
(4,)


In [26]:
a5.shape == a1.shape

False

In [30]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [34]:
import re
s = 'ACBCAC'
re.findall('^AC', s)

['A']

In [39]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

print(result)




['A', 'AA', 'AA', 'AA', 'A']


In [42]:
phone = "Office of Research Administration: (734) 647-6333 | 4325 North Quad
Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205
Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500
Office of the Dean: (734) 647-3576 | 4322 North Quad
UMSI Engagement Center: (734) 763-1251 | 777 North University
Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad"

SyntaxError: EOL while scanning string literal (<ipython-input-42-e3d2fea10c41>, line 1)

In [47]:
text=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''

import re

pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4
